server:
  port: 8888

spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro

mybatis:
  type-aliases-package: fun.zrbac.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png
